
export interface Operator {
  id: string;
  name: string;
  cargo?: string;
  setor?: string;
}

export interface Equipment {
  id: string;
  name: string;
  kp: string;
  sector: string;
  capacity: string;
  type: string;
}

export interface ChecklistItem {
  id: string;
  question: string;
  answer: "Sim" | "Não" | "N/A" | "Selecione" | null;
}

// Lista de operadores atualizada com os dados fornecidos pelo cliente
export const operators: Operator[] = [
  { id: "1260", name: "VALDAIR LAURENTINO", cargo: "OPER. PRODUÇÃO MACHARIA III", setor: "MACHARIA" },
  { id: "1325", name: "GILMAR OTEMBRAIT", cargo: "INSPETOR QUALIDADE II", setor: "CONTROLE DE QUALIDADE" },
  { id: "1329", name: "GEISON CRISTIANO SCHEL", cargo: "OPER MAQ MOLD FECH II", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "1372", name: "ADEMAR GESSER", cargo: "OP. REBARBAÇÃO (OP. ACAB.)III", setor: "REBOLO PENDULAR" },
  { id: "1382", name: "SILVERIO BISATTO", cargo: "SOLDADOR II", setor: "SOLDA" },
  { id: "1413", name: "FABRICIO DALLABONA", cargo: "ENCAR. DE PROD. ACABAMENTO II", setor: "ACABAMENTO DE PEÇAS (I)" },
  { id: "1422", name: "JOSE MARINO REICHERT", cargo: "OP. REBARBAÇÃO (OP. ACAB.)III", setor: "REBOLO PENDULAR" },
  { id: "1423", name: "JOSE PEREIRA", cargo: "INSPETOR QUALIDADE IV", setor: "CONTROLE DE QUALIDADE" },
  { id: "1429", name: "EDILSON NEVES MOTTA", cargo: "INSPETOR QUALIDADE II", setor: "CONTROLE DE QUALIDADE" },
  { id: "1430", name: "REGINALDO VALERIANO DOS SANTOS", cargo: "OP. COR. CANAL (MAÇARIQ.) III", setor: "CORTE DE CANAL MAÇARICO" },
  { id: "1437", name: "ANDERSON LUIS ONEDA", cargo: "MODELADOR III", setor: "MODELARIA" },
  { id: "1446", name: "JOAO CARLOS VANELLI", cargo: "OP. COR. CANAL (MAÇARIQ.) III", setor: "CORTE DE CANAL MAÇARICO" },
  { id: "1463", name: "RAFAEL CLEMENTE ESPIG", cargo: "OPER. PRODUÇÃO MACHARIA III", setor: "MACHARIA" },
  { id: "1475", name: "MARCELO RAMOS", cargo: "MECÂNICO MANUTENÇÃO III", setor: "MANUTENÇAO MECANICA" },
  { id: "1478", name: "ADENOR REICHELT", cargo: "OPER. DE FORNO A INDUÇÃO III", setor: "FUSAO" },
  { id: "1479", name: "ADELSIO REICHELT", cargo: "REFRATARISTA II", setor: "FUSAO" },
  { id: "1488", name: "EDIVAN VELOZO", cargo: "INSPETOR QUALIDADE II", setor: "CONTROLE DE QUALIDADE" },
  { id: "1493", name: "ROBERTO CARLOS PEREIRA", cargo: "OPER. PRODUÇÃO MACHARIA III", setor: "MACHARIA" },
  { id: "1501", name: "EDELBERTO CARLOS GESSER", cargo: "OPERADOR PONTE ROLANTE II", setor: "ACABAMENTO DE PEÇAS" },
  { id: "1508", name: "OSNI REICHERT", cargo: "INSPETOR QUALIDADE II", setor: "CONTROLE DE QUALIDADE" },
  { id: "1526", name: "ROGERIO JOSÉ REICHELT", cargo: "OPER. PRODUÇÃO MOLDAGEM III", setor: "MOLDAGEM" },
  { id: "1529", name: "JOAO MARQUES", cargo: "OPER PROD MOLD FECH III", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "1536", name: "VALDEMIRO LEPINSKI", cargo: "MECÂNICO MANUTENÇÃO II", setor: "MANUTENÇAO MECANICA" },
  { id: "1543", name: "GUILHERME LEMKE", cargo: "SUPERVISOR DE USINAGEM", setor: "USINAGEM (I)" },
  { id: "1546", name: "EDERSON SCABURRI", cargo: "LIDER DA ELETROMECANICA", setor: "MANUTENÇAO ELETRICA" },
  { id: "1549", name: "SAMUEL FELIPE KREHNKE", cargo: "MECÂNICO MANUTENÇÃO II", setor: "MANUTENÇAO MECANICA" },
  { id: "1552", name: "JAIME LEPINSKI", cargo: "TORNEIRO MEC. (OPER. USI.)I", setor: "USINAGEM" },
  { id: "1567", name: "ALANO COSTA BATISTA", cargo: "OPERADOR DE FORNO A INDUÇÃO II", setor: "FUSAO" },
  { id: "1575", name: "FABIANO SIGNORELLI", cargo: "OPER.TRATAMENTO TÉRMICO I", setor: "TRATAMENTO TÉRMICO" },
  { id: "1592", name: "ANDERSON DA CUNHA", cargo: "SOLDADOR II", setor: "SOLDA" },
  { id: "1607", name: "JOCEMAR ROSA DOS SANTOS", cargo: "OPER. PRODUÇÃO MACHARIA III", setor: "MOLDAGEM COLDBOX" },
  { id: "1618", name: "ROSALVO MACHADO", cargo: "SOLDADOR III", setor: "SOLDA" },
  { id: "1638", name: "LEONARDO SCHUTZ SCHAUSS", cargo: "OP. DE ESCARFAGEM (OP. ACB)II", setor: "ESCARFAGEM" },
  { id: "1739", name: "EDJALMA RICARDO MARIANO", cargo: "OPER. PRODUÇÃO MACHARIA III", setor: "MACHARIA" },
  { id: "1757", name: "WALLACE ALVES DE JESUS", cargo: "OPER PROD MOLD FECH III", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "1760", name: "ELOIR RAMALHO", cargo: "INSP. QUALIDADE DIMENSIONAL II", setor: "CONTROLE DE QUALIDADE DIMENSIONAL" },
  { id: "1776", name: "JOAO CARLOS RODRIGUES", cargo: "OPER. DE JATO (OPER. ACAB.)II", setor: "ROTOJATO" },
  { id: "1782", name: "ALTOIR FERNANDES DA SILVA", cargo: "OPER. PRODUÇÃO MACHARIA III", setor: "MOLDAGEM COLDBOX" },
  { id: "1829", name: "ELIEL PEREIRA FERNANDES", cargo: "OPER. PRODUÇÃO MACHARIA IV", setor: "DEP. QUIMICOS E INFLAMAVEIS" },
  { id: "1832", name: "CARLOS EDUARDO BAADER", cargo: "OPERADOR PONTE ROLANTE II", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "1898", name: "MAURO SERGIO GONCALVES DA SILVA", cargo: "SOLDADOR III", setor: "SOLDA" },
  { id: "1899", name: "IZALTINO ALBERTO SOARES", cargo: "MECÂNICO MANUTENÇÃO III", setor: "MANUTENÇAO MECANICA" },
  { id: "3426", name: "ANDRE LUIS BAADER", cargo: "ELETRICISTA II", setor: "MANUTENÇAO ELETRICA" },
  { id: "1911", name: "ARLINDO EDUARDO OTEMBRAIT", cargo: "PANELEIRO (OPER. VAZAMENTO)II", setor: "VAZAMENTO" },
  { id: "1949", name: "EDSON KREUCH", cargo: "ELETRICISTA II", setor: "MANUTENÇAO ELETRICA" },
  { id: "1956", name: "ALFREDO FIAMONCINI JUNIOR", cargo: "MODELADOR III", setor: "MODELARIA" },
  { id: "1969", name: "IVAN KRAISCH", cargo: "SUPERVISOR MANUTENÇÃO", setor: "MANUTENÇAO ELETRICA" },
  { id: "1972", name: "ALTAMIR BORGES", cargo: "MODELADOR III", setor: "MODELARIA" },
  { id: "1974", name: "MARIO LOTERIO", cargo: "OPER. PRODUÇÃO MACHARIA II", setor: "MACHARIA" },
  { id: "1982", name: "SIDNEI HABITZREITER", cargo: "OPER PROD MOLD FECH II", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "1985", name: "GILSON DE CASTRO", cargo: "ENCARREGADO MACHARIA", setor: "MACHARIA (I)" },
  { id: "1992", name: "CARLOS DOS SANTOS", cargo: "OPER. PRODUÇÃO MOLDAGEM III", setor: "MOLDAGEM" },
  { id: "2001", name: "ELBERT FERREIRA", cargo: "INSPETOR QUALIDADE III", setor: "CONTROLE DE QUALIDADE" },
  { id: "2007", name: "LUCIANO LUCAS CAMARGO PEDROSO", cargo: "INSPETOR QUALIDADE II", setor: "CONTROLE DE QUALIDADE" },
  { id: "2009", name: "LEONEL GONSALES QUIMENES", cargo: "ENCARREGADO DE FUSAO", setor: "FUSÃO (I)" },
  { id: "2018", name: "JOSE CARLOS PEREIRA", cargo: "OP. REBARBAÇÃO (OP. ACAB.)III", setor: "REBOLO PENDULAR" },
  { id: "2020", name: "SIDINEY DA SILVA PEREIRA", cargo: "OPER PROD MOLD FECH III", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "2026", name: "WILSON ANTONIO DA LUZ", cargo: "AUXILIAR SERV. GERAIS I", setor: "SERVIÇOS GERAIS" },
  { id: "2053", name: "CARLOS SCHNAIDER", cargo: "LIDER DA ELETROMECANICA", setor: "MANUTENÇAO ELETRICA" },
  { id: "2055", name: "FABIO ESPIG", cargo: "OP. REBARBAÇÃO (OP. ACAB.)III", setor: "REBOLO PENDULAR" },
  { id: "2548", name: "ELIAS FRANHER", cargo: "OPERADOR PONTE ROLANTE II", setor: "ACABAMENTO DE PEÇAS" },
  { id: "2721", name: "JOAO PAULO DA COSTA", cargo: "OPER. DE JATO (OPER. ACAB.)II", setor: "JATO GRANALHA" },
  { id: "2725", name: "MARCELO HENQUE GONÇALVES", cargo: "OPERADOR EMPILHADEIRA III", setor: "EXPEDIÇÃO" },
  { id: "2726", name: "ALATHAN JHONATAN GONÇALVES PONTES", cargo: "OPER. DE JATO (OPER. ACAB.)II", setor: "JATO GRANALHA" },
  { id: "2734", name: "MARCELO DE SOUZA CARDOSO", cargo: "OPER. DE FORNO A INDUÇÃO III", setor: "FUSAO" },
  { id: "2752", name: "VALDEMIR PEREIRA DE SOUZA", cargo: "OPER. REBARBAÇÃO (OP. ACAB.) II", setor: "PONTA MONTADA" },
  { id: "2753", name: "FRANCISCO CARLOS SANTOS SILVA JUNIOR", cargo: "OPER. DE JATO (OPER. ACAB.)I", setor: "JATO GRANALHA" },
  { id: "2759", name: "ELIZANDRO MEURER", cargo: "OPER. DE PROD. DESMOLDAGEM II", setor: "DESMOLDAGEM" },
  { id: "2762", name: "DANIEL GONCALVES DE JESUS", cargo: "OPER. REBARBAÇÃO (OP. ACAB.)II", setor: "LIXADEIRA MANUAL" },
  { id: "2763", name: "NAZARENO SILVA DOS SANTOS", cargo: "OPER. DE JATO (OPER. ACAB.)II", setor: "JATO GRANALHA" },
  { id: "2798", name: "CRISTIAN RIBEIRO DOMINGUES", cargo: "OPER. DE PROD. DESMOLDAGEM II", setor: "DESMOLDAGEM" },
  { id: "2807", name: "SERGIO PEREIRA JUNIOR", cargo: "INSPETOR QUALIDADE I", setor: "CONTROLE DE QUALIDADE" },
  { id: "2815", name: "RODRIGO SCHWEITZER", cargo: "EXPEDIDOR I", setor: "EXPEDIÇÃO" },
  { id: "2816", name: "FRANCISCO ANTONIO RODRIGUES JUNIOR", cargo: "OP. REBARBAÇÃO (OP. ACAB.)III", setor: "PONTA MONTADA" },
  { id: "2830", name: "DEYMISON SILVA ROSA", cargo: "OPER. DE ESCARFAGEM (OP. ACB)I", setor: "CORTE DE CANAL INOX" },
  { id: "2853", name: "ARNALDO SOUSA RODRIGUES", cargo: "OPER. DE JATO (OPER. ACAB.)I", setor: "ROTOJATO" },
  { id: "2896", name: "LINCOLN GUSTAVO S FERNANDES DA SILVA", cargo: "ELETRIC. DESENVOL. I", setor: "MANUTENÇAO ELETRICA" },
  { id: "2907", name: "ALESSANDRO SANTANA", cargo: "SOLDADOR II", setor: "SOLDA" },
  { id: "2915", name: "ALEXANDRE ALEX DE LIMA CORREA", cargo: "OPER. PRODUÇÃO MACHARIA II", setor: "MACHARIA" },
  { id: "2932", name: "ERIC GUTZ AMORIM", cargo: "OP. DE ESCARFAGEM (OP. ACB)II", setor: "ESCARFAGEM" },
  { id: "2934", name: "ATILLA SANTOS CONCEICAO", cargo: "OPER. DE ESCARFAGEM (OP. ACB)I", setor: "ESCARFAGEM" },
  { id: "2964", name: "RAMILSON GUERRA MATOS", cargo: "OP. COR. CANAL (MAÇARIQ.) II", setor: "CORTE DE CANAL MAÇARICO" },
  { id: "2974", name: "PEDRO HENRIQUE DOS SANTOS", cargo: "OPER PROD MOLD FECH II", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "3010", name: "LUCAS ALVES DOS SANTOS", cargo: "OPER. REBARBAÇÃO (OP. ACAB.)II", setor: "LIXADEIRA MANUAL" },
  { id: "3022", name: "ANTONIO CARLOS EMILIO", cargo: "OP. DE ESCARFAGEM (OP. ACB)II", setor: "ESCARFAGEM" },
  { id: "3026", name: "MATHEUS MARIETO ADURENS", cargo: "FRESADOR (OPER. USINAGEM)I", setor: "USINAGEM" },
  { id: "3028", name: "JOAO AUGUSTO DE SOUZA OLIVEIRA", cargo: "OPER. DE PROD. DESMOLDAGEM I", setor: "DESMOLDAGEM" },
  { id: "3029", name: "RODRIGO DA SILVA LEITE", cargo: "PANELEIRO (OPER. VAZAMENTO)II", setor: "VAZAMENTO" },
  { id: "3037", name: "DOUGLAS DE SOUSA DOS SANTOS", cargo: "OPER. REBARBAÇÃO (OP. ACAB.)II", setor: "LIXADEIRA MANUAL" },
  { id: "3058", name: "ELVIS AUGUSTO DE LIMA", cargo: "OPER. PRODUÇÃO MACHARIA II", setor: "MACHARIA" },
  { id: "3069", name: "PAULO AUGUSTO DE AMARAL", cargo: "PANELEIRO (OPER. VAZAMENTO)I", setor: "FUSAO" },
  { id: "3076", name: "LUCIANO JOSE DOS SANTOS", cargo: "OPER PROD MOLD FECH II", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "3080", name: "ERIC ALVES DA LUZ", cargo: "OPER PROD MOLD FECH II", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "3105", name: "LINOSIR MARTINS DOS SANTOS", cargo: "OPERADOR DE PRODUÇÃO (SUCATA)I", setor: "SUCATA" },
  { id: "3106", name: "RUAN CARLOS FLORIANI", cargo: "INSPETOR QUALIDADE I", setor: "CONTROLE DE QUALIDADE" },
  { id: "3108", name: "ALEXANDRE THEISS", cargo: "SOLDADOR II", setor: "SOLDA" },
  { id: "3110", name: "PEDRO HENRIQUE DA SILVA DE CARVALHO", cargo: "OPER. PRODUÇÃO MACHARIA I", setor: "MOLDAGEM COLDBOX" },
  { id: "3113", name: "ROBSON SANTOS DA CONCEIÇÃO", cargo: "OPER PROD MOLD FECH II", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "3115", name: "JOAO PAULO BELO DA SILVA", cargo: "OPER. DE PROD. DESMOLDAGEM I", setor: "DESMOLDAGEM" },
  { id: "3117", name: "FERNANDO SEVERINO DA SILVA", cargo: "FRESADOR (OPER. USINAGEM)I", setor: "USINAGEM" },
  { id: "3130", name: "SAYMON CORREA SILVEIRA DE ARAUJO", cargo: "MONTADOR I", setor: "MANUTENÇAO MECANICA" },
  { id: "3133", name: "HELIO RENATO SOUSA DE CARVALHO", cargo: "OPER. DE PRODUÇÃO (SUCATA)II", setor: "SUCATA" },
  { id: "3141", name: "MIZAEL DE ARAUJO DE OLIVEIRA", cargo: "ELETRICISTA DESENVOLV. II", setor: "MANUTENÇAO ELETRICA" },
  { id: "3142", name: "ATILIO MARINO MARTINI DOS SANTOS", cargo: "MODELADOR I", setor: "MODELARIA" },
  { id: "3149", name: "YURI LHORAN SANTOS OLIVEIRA", cargo: "OPER. DE PROD. DESMOLDAGEM I", setor: "DESMOLDAGEM" },
  { id: "3151", name: "REGINALDO EVARISTO DO NASCIMENTO", cargo: "OPERADOR DE PRODUÇÃO (SUCATA)I", setor: "SUCATA" },
  { id: "3153", name: "JADER LUIS ZIBELL", cargo: "LIDER DE PRODUÇÃO ACABAMENTO I", setor: "ACABAMENTO DE PEÇAS (I)" },
  { id: "3162", name: "FRANCISCO HELIO GOMES DE SOUSA", cargo: "OPER PROD MOLD FECH I", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "3165", name: "JOSE MARCELO DOS SANTOS", cargo: "OPER. PRODUÇÃO MACHARIA II", setor: "MACHARIA" },
  { id: "3173", name: "ALEX DE JESUS DOS SANTOS", cargo: "OPER. DE JATO (OPER. ACAB.)I", setor: "ROTOJATO" },
  { id: "3178", name: "CRISTIANO MULLER MERENCIO", cargo: "MONTADOR I", setor: "MANUTENÇAO MECANICA" },
  { id: "3208", name: "JORGE VICENTE DOS SANTOS", cargo: "OPER. PRODUÇÃO MACHARIA I", setor: "MACHARIA" },
  { id: "3209", name: "NATANIEL VIEIRA AIRES", cargo: "OPER. DE PROD. DESMOLDAGEM I", setor: "DESMOLDAGEM" },
  { id: "3214", name: "RIAN DA ROSA CHAGAS", cargo: "INSPETOR QUALIDADE I", setor: "CONTROLE DE QUALIDADE" },
  { id: "3217", name: "DAVI RODRIGUES DOS SANTOS", cargo: "PANELEIRO (OPER. VAZAMENTO)I", setor: "FUSAO" },
  { id: "3233", name: "ANTONIO DE GUSMAO DIAS", cargo: "OPER. PRODUÇÃO MACHARIA II", setor: "MOLDAGEM COLDBOX" },
  { id: "3238", name: "TAUA DE JESUS SANTOS", cargo: "OPER PROD MOLD FECH I", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "3246", name: "RICARDO GUIMARAES DE OLIVEIRA", cargo: "INSPETOR QUALIDADE I", setor: "CONTROLE DE QUALIDADE" },
  { id: "3250", name: "AMANTINO COSTA DE PAULA", cargo: "MECÂNICO MANUTENÇÃO I", setor: "MANUTENÇAO MECANICA" },
  { id: "3254", name: "ERICK THIAGO NEVES DE SOUZA", cargo: "OPER PROD MOLD FECH I", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "3263", name: "JOSE VITOR COSTA DA CRUZ", cargo: "OPER. PRODUÇÃO MACHARIA I", setor: "MACHARIA" },
  { id: "3269", name: "WESLEY SILVA ARAUJO", cargo: "OPER. REBARBAÇÃO (OP. ACAB.)I", setor: "PONTA MONTADA" },
  { id: "3272", name: "JEAN MARCELO DA SILVA", cargo: "OP. REBARBAÇÃO (OP. ACAB.)III", setor: "ACABAMENTO DE PEÇAS" },
  { id: "3274", name: "PEDRO LUCAS SOUZA SANTOS", cargo: "OPERADOR DE PRODUÇÃO (SUCATA)I", setor: "SUCATA" },
  { id: "3275", name: "JOAO HENRIQUE BATISTA DANTAS", cargo: "INSPETOR QUALIDADE I", setor: "CONTROLE DE QUALIDADE" },
  { id: "3276", name: "KEVYN BRYAN DA SILVA FIGUEIRA", cargo: "AUXILIAR MODELARIA", setor: "MODELARIA" },
  { id: "3284", name: "LUCAS HENRIQUE LUNA CAMARGO", cargo: "OPER. DE ESCARFAGEM (OP. ACB)I", setor: "ESCARFAGEM" },
  { id: "3291", name: "TIAGO NUNES SANTOS", cargo: "ELETRICISTA DESENVOLV. II", setor: "MANUTENÇAO ELETRICA" },
  { id: "3302", name: "GUSTAVO DOS SANTOS GOMES", cargo: "OPER. PRODUÇÃO MACHARIA I", setor: "MACHARIA" },
  { id: "3303", name: "LUCAS RICARDO BERTE SILVA", cargo: "OPER PROD MOLD FECH I", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "3314", name: "THIAGO DOS SANTOS GOMES", cargo: "OPER. DE JATO (OPER. ACAB.)I", setor: "ROTOJATO" },
  { id: "3316", name: "NIVALDO KLEINE", cargo: "TORNEIRO MEC. (OPER. USI.)I", setor: "USINAGEM" },
  { id: "3323", name: "JOAO VITOR FERREIRA RODRIGUES", cargo: "OPERADOR DE PRODUÇÃO (SUCATA)I", setor: "SUCATA" },
  { id: "3324", name: "MATEUS JOSIVAN DE MORAES MADUREIRA", cargo: "OPER. PRODUÇÃO MACHARIA I", setor: "MOLDAGEM COLDBOX" },
  { id: "3326", name: "MARCO ANTONIO KLEIS", cargo: "INSPETOR QUALIDADE I", setor: "CONTROLE DE QUALIDADE" },
  { id: "3332", name: "SOPHIA AMABILE ESPIG", cargo: "ASSISTENTE ADMINISTRATIVO", setor: "SGA" },
  { id: "3334", name: "PAULO MAURICIO DE SOUZA BARROSO", cargo: "MECANICO DESENVOLV. I", setor: "MANUTENÇAO MECANICA" },
  { id: "3336", name: "IGOR CHARLES XAVIER SILVA", cargo: "AUXILIAR DE PRODUÇÃO", setor: "MACHARIA" },
  { id: "3347", name: "EDUARDO FRANCISCO MAIS", cargo: "OPER. REBARBAÇÃO (OP. ACAB.)I", setor: "LIXADEIRA MANUAL" },
  { id: "3353", name: "EVERTON MACHADO DOCHVAT", cargo: "AUX.CONTROLE QUALIDADE FINAL", setor: "CONTROLE DE QUALIDADE" },
  { id: "3365", name: "WILLIAN LEONEL DA ROSA", cargo: "SOLDADOR II", setor: "SOLDA" },
  { id: "3372", name: "IJARISSON SANTOS DA SILVA", cargo: "AUXILIAR DE PRODUÇÃO", setor: "MACHARIA" },
  { id: "3375", name: "WELLIGTON SOUSA LOBO", cargo: "MECÂNICO MANUTENÇÃO I", setor: "MANUTENÇAO MECANICA" },
  { id: "3376", name: "KAREU TELEGINSKI TANNER", cargo: "ELETRICISTA I", setor: "MANUTENÇAO ELETRICA" },
  { id: "3377", name: "WELLINGTON CRYSTIAN DA HORA OLIVEIRA", cargo: "ELETRICISTA I", setor: "MANUTENÇAO ELETRICA" },
  { id: "3399", name: "ROGERIO TAVARES", cargo: "OPER. PRODUÇÃO MACHARIA I", setor: "MACHARIA" },
  { id: "3402", name: "AUGUSTO SANTANA MORAES", cargo: "AUXILIAR DE PRODUÇÃO", setor: "MACHARIA" },
  { id: "3409", name: "GABRIEL NASCIMENTO DA SILVA SCHAUSS", cargo: "OPER. PRODUÇÃO MACHARIA I", setor: "MACHARIA" },
  { id: "3410", name: "WELLINGTON MARTINS VIANA BRETAS", cargo: "AUXILIAR DE PRODUÇÃO", setor: "PONTA MONTADA" },
  { id: "3411", name: "JHEIMISON DA SILVA LUZ", cargo: "OPER. PRODUÇÃO MACHARIA I", setor: "MACHARIA" },
  { id: "3420", name: "LUCAS DA SILVA DE CARVALHO", cargo: "AUXILIAR MODELARIA", setor: "MODELARIA" },
  { id: "3421", name: "GABRIEL SIEBERT HUGEN", cargo: "AUXILIAR MODELARIA", setor: "MARCENARIA" },
  { id: "3422", name: "ALESSANDRO BRESSANINI", cargo: "ELETRICISTA I", setor: "MANUTENÇAO ELETRICA" },
  { id: "3425", name: "JAIME GUSTAVO GADOTTI", cargo: "MECÂNICO MANUTENÇÃO II", setor: "MANUTENÇAO MECANICA" },
  { id: "3430", name: "ISLAN SOARES SANTOS", cargo: "AUXILIAR MECANICO", setor: "MANUTENÇAO MECANICA" },
  { id: "3432", name: "NATHANAEL SCHENK MATHEUS", cargo: "MECÂNICO MANUTENÇÃO II", setor: "MANUTENÇAO MECANICA" },
  { id: "3433", name: "JOSE MARIO CORDEIRO", cargo: "MECÂNICO MANUTENÇÃO II", setor: "MANUTENÇAO MECANICA" },
  { id: "3434", name: "EDESIO MARCOS DA SILVA", cargo: "AUXILIAR DE USINAGEM", setor: "USINAGEM" },
  { id: "3437", name: "GUSTAVO FERNANDES PEREIRA", cargo: "AUXILIAR DE PRODUÇÃO", setor: "MACHARIA" },
  { id: "3438", name: "JHONATA FELIX DOS SANTOS", cargo: "AUXILIAR DE PRODUÇÃO", setor: "DESMOLDAGEM" },
  { id: "3442", name: "RONALD SANTOS DE CASTRO", cargo: "AUXILIAR DE PRODUÇÃO", setor: "MACHARIA" },
  { id: "3443", name: "TIAGO JOSE DE SOUZA", cargo: "AUXILIAR DE PRODUÇÃO", setor: "LIXADEIRA MANUAL" },
  { id: "3444", name: "RENATO RONCHI", cargo: "TORNEIRO MEC. (OPER. USI.)I", setor: "USINAGEM" },
  { id: "3446", name: "ARISTIDES RIBEIRO", cargo: "MECÂNICO MANUTENÇÃO I", setor: "MANUTENÇAO MECANICA" },
  { id: "3451", name: "RODRIGO DE CARVALHO MARTINS", cargo: "MECÂNICO MANUTENÇÃO I", setor: "MANUTENÇAO MECANICA" },
  { id: "3466", name: "JOSE CARLOS FERREIRA DE SA", cargo: "AUXILIAR DE PRODUÇÃO", setor: "ACABAMENTO DE PEÇAS" },
  { id: "3467", name: "JOSE DEIVISON SOARES MARTINS", cargo: "AUXILIAR DE PRODUÇÃO", setor: "ACABAMENTO DE PEÇAS" },
  { id: "3472", name: "MATHEUS DE JESUS SANTOS", cargo: "", setor: "ACABAMENTO DE PEÇAS" },
  { id: "3474", name: "SEVERINO DO RAMO SALUSTIANO", cargo: "AUXILIAR DE PRODUÇÃO", setor: "ACABAMENTO DE PEÇAS" },
  { id: "3490", name: "ALISSON ALIOMAR DE LIMA SILVA", cargo: "AUXILIAR DE PRODUÇÃO", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "3526", name: "PATRICK RUAN FLORENCIO DE JESUS", cargo: "AUX.CONTROLE QUALIDADE FINAL", setor: "CONTROLE DE QUALIDADE" },
  { id: "3529", name: "JOSE PAULO ANDRADE SANTOS", cargo: "AUXILIAR DE PRODUÇÃO", setor: "ACABAMENTO DE PEÇAS" },
  { id: "3543", name: "ISAAC SOUZA DE LIMA", cargo: "AUXILIAR DE PRODUÇÃO", setor: "ACABAMENTO DE PEÇAS" },
  { id: "3545", name: "EMERSON BARROS OLIVEIRA", cargo: "AUXILIAR DE PRODUÇÃO", setor: "ACABAMENTO DE PEÇAS (I)" },
  { id: "3554", name: "DAVI SANTOS CORDEIRO", cargo: "AUXILIAR DE PRODUÇÃO", setor: "ACABAMENTO DE PEÇAS" },
  { id: "3561", name: "THIAGO GABRIEL NASCIMENTO FERREIRA", cargo: "AUXILIAR DE PRODUÇÃO", setor: "ACABAMENTO DE PEÇAS" },
  { id: "3571", name: "LUCAS SILVA COSTA", cargo: "SOLDADOR I", setor: "SOLDA" },
  { id: "3581", name: "LEONARDO CARLOS DA SILVA LIMA", cargo: "AUXILIAR DE PRODUÇÃO", setor: "MOLDAGEM" },
  { id: "1363", name: "FELIPE DALLABONA", cargo: "ANALISTA DE PPCP II", setor: "PROGRAMÇAO PROD." },
  { id: "1377", name: "CELSO DA SILVA PEREIRA", cargo: "TÉCNICO EM SEGURANÇA DO TRABALHO II", setor: "SEG. MEDICINA TRABA." },
  { id: "1514", name: "MAURICIO MELCHIORETTO", cargo: "ANALISTA DE PROCESSOS TÉCNICO I", setor: "DEP. TÉCNICO" },
  { id: "1694", name: "LUIS ANTONIO PEREIRA DO NASCIMENTO", cargo: "ALMOXARIFE DE MODELOS I", setor: "PROGRAMÇAO PROD." },
  { id: "1309", name: "LUIS CARLOS REICHERT", cargo: "ENCARREGADO C.Q.F II", setor: "ACABAMENTO DE PEÇAS (I)" },
  { id: "1500", name: "EDSON JOSE GONÇALVES", cargo: "ANALISTA QUALIDADE III", setor: "QUALIDADE" },
  { id: "1509", name: "CARLOS EDUARDO ZIMERMANN", cargo: "ENCARREGADO MACHARIA II", setor: "MACHARIA (I)" },
  { id: "1542", name: "HORST ALBERTO SCHILL", cargo: "LIDER MODELAÇÃO", setor: "MODELARIA (I)" },
  { id: "1733", name: "ROSANGELA HARTMANN", cargo: "COORDENADOR DA QUALIDADE", setor: "QUALIDADE" },
  { id: "1929", name: "VANDERSON DONATO RECH MACHADO", cargo: "LIDER DE PRODUÇÃO ACABAMENTO I", setor: "ACABAMENTO DE PEÇAS (I)" },
  { id: "2059", name: "LUIS HENRIQUE MACHADO PEREIRA", cargo: "OPERADOR PONTE ROLANTE I", setor: "ACABAMENTO DE PEÇAS" },
  { id: "2066", name: "EDELCIO AMORIM", cargo: "OP. COR. CANAL (MAÇARIQ.) II", setor: "CORTE DE CANAL MAÇARICO" },
  { id: "2086", name: "CARLOS HABITZREITER", cargo: "MECANICO DESENVOLV. II", setor: "MANUTENÇAO MECANICA" },
  { id: "2090", name: "CARLOS EDUARDO VANELLI", cargo: "OPER. REBARBAÇÃO (OP. ACAB.) II", setor: "ACABAMENTO DE PEÇAS" },
  { id: "2092", name: "RAFAEL BATISTA", cargo: "ENCARREGADO DE FUSAO", setor: "FUSÃO (I)" },
  { id: "2131", name: "CLAUDEMIR PEREIRA LIMA", cargo: "MECÂNICO MANUTENÇÃO I", setor: "MANUTENÇAO MECANICA" },
  { id: "2157", name: "MATHEUS GUSTAVO DE CAMARGO PEDROSO", cargo: "OPER. PRODUÇÃO MOLDAGEM II", setor: "MOLDAGEM" },
  { id: "2159", name: "GILIARD ROBERTO DA LUZ", cargo: "TORNEIRO MEC. (OPER. USI.)II", setor: "USINAGEM" },
  { id: "2169", name: "JOANDERSON DAVISSON BARBOSA DOS SANTOS", cargo: "OPER. DE SISTEMA DE AREIA III", setor: "DESMOLDAGEM" },
  { id: "2176", name: "ADEMAR GILDO DA COSTA", cargo: "OP. REBARBAÇÃO (OP. ACAB.)III", setor: "ACABAMENTO DE PEÇAS" },
  { id: "2178", name: "RENE CYRO SIMAS JUNIOR", cargo: "LIDER DE PRODUÇÃO ACABAMENTO II", setor: "ACABAMENTO DE PEÇAS (I)" },
  { id: "2182", name: "LUCAS EDUARDO DE QUEIROZ DA SILVA", cargo: "SOLDADOR II", setor: "SOLDA" },
  { id: "2193", name: "PAULO LINCON CAVALCANTI GIMENES", cargo: "INSPETOR QUALIDADE II", setor: "CONTROLE DE QUALIDADE" },
  { id: "2194", name: "CLAUDENIR DA SILVA", cargo: "OPER. REBARBAÇÃO (OP. ACAB.) II", setor: "LIXADEIRA MANUAL" },
  { id: "2209", name: "ARLEM DOS SANTOS VARGAS JUNIOR", cargo: "ENCARREGADO MACHARIA", setor: "MACHARIA (I)" },
  { id: "2235", name: "ALTINO DOS SANTOS", cargo: "SOLDADOR II", setor: "SOLDA" },
  { id: "2246", name: "GUILHERME MULLER S. FERNANDES DA SILVA", cargo: "ELETRIC. DESENVOL. I", setor: "MANUTENÇAO ELETRICA" },
  { id: "2252", name: "WAGNER COSTA DAMACENO", cargo: "INSPETOR QUALIDADE II", setor: "CONTROLE DE QUALIDADE" },
  { id: "2258", name: "WASHINGTON SILVA DOS SANTOS", cargo: "OPER MAQ MOLD FECH II", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "2283", name: "CICERO FELINTO DA SILVA", cargo: "SOLDADOR II", setor: "SOLDA" },
  { id: "2319", name: "LUIS FERNANDO VINTER WILL", cargo: "MODELADOR II", setor: "MODELARIA" },
  { id: "2320", name: "EMERSON ROBERTO RAMOS", cargo: "FRESADOR CNC (MODELAÇÃO) II", setor: "MODELARIA" },
  { id: "2326", name: "ROBERTO GAIO", cargo: "OPERADOR PONTE ROLANTE II", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "2368", name: "FERNANDO DALLABONA", cargo: "LIDER TRATAMENTO TÉRMICO", setor: "TRATAMENTO TÉRMICO" },
  { id: "2374", name: "ROGERIO DOS SANTOS SOUZA", cargo: "OP. REBARBAÇÃO (OP. ACAB.)III", setor: "REBOLO PENDULAR" },
  { id: "2385", name: "ADRIANO MARTENDAL", cargo: "MODELADOR IV", setor: "MODELARIA" },
  { id: "2393", name: "ALEXANDRE SCHVAMBACH", cargo: "EXPEDIDOR II", setor: "EXPEDIÇÃO" },
  { id: "2405", name: "JONATHAN PAULO SADOSKI", cargo: "OPERADOR EMPILHADEIRA II", setor: "ACABAMENTO DE PEÇAS (I)" },
  { id: "2408", name: "JADERSON EDUARDO RAMOS", cargo: "FRESADOR CNC (MODELAÇÃO) II", setor: "MODELARIA" },
  { id: "2409", name: "SILVIO ANTUNES", cargo: "OPER. PRODUÇÃO MACHARIA III", setor: "MACHARIA" },
  { id: "2413", name: "WILLIAM DIAS DA SILVA", cargo: "OPER PROD MOLD FECH III", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "2421", name: "ELIEL DE LIMA ROSENO", cargo: "ELETRICISTA DESENVOLV. II", setor: "MANUTENÇAO ELETRICA" },
  { id: "2429", name: "PAULO SERGIO SANTOS JUNIOR", cargo: "OPER PROD MOLD FECH III", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "2432", name: "JOSE RODOLFO REICHELT", cargo: "OPER PROD MOLD FECH III", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "2439", name: "WESLEY DE AMORIM SILVA", cargo: "MODELADOR I", setor: "MODELARIA" },
  { id: "2447", name: "DJONATHAM MACEDO", cargo: "SOLDADOR II", setor: "SOLDA" },
  { id: "2450", name: "JOÃO BATISTA DA ROCHA", cargo: "OPER. PRODUÇÃO MACHARIA II", setor: "MOLDAGEM COLDBOX" },
  { id: "2454", name: "RAIMUNDO LIRA DE MIRANDA", cargo: "OP. COR. CANAL (MAÇARIQ.) II", setor: "CORTE DE CANAL MAÇARICO" },
  { id: "2463", name: "LUIS DONIZETE LUCOLI", cargo: "OPER. DE FORNO A INDUÇÃO III", setor: "FUSAO" },
  { id: "2467", name: "RENAN DOS SANTOS MARANGONI", cargo: "OPER. PRODUÇÃO MACHARIA II", setor: "DEP. QUIMICOS E INFLAMAVEIS" },
  { id: "2472", name: "JOSE ADAUTO ALVES DE GOES", cargo: "OPERADOR EMPILHADEIRA III", setor: "EXPEDIÇÃO" },
  { id: "2523", name: "MICHAEL ALAN PAIVA DA CRUZ", cargo: "OP. COR. CANAL (MAÇARIQ.) II", setor: "CORTE DE CANAL MAÇARICO" },
  { id: "2525", name: "JOSE MARIA FARIAS DO COUTO FILHO", cargo: "OPER. DE JATO (OPER. ACAB.)II", setor: "JATO GRANALHA" },
  { id: "2530", name: "GUILHERME KREUCH", cargo: "OPERADOR CAD E CAM I", setor: "MODELARIA (I)" },
  { id: "2546", name: "MARLOS GRAF", cargo: "OPER. DE PRODUÇÃO (SUCATA)II", setor: "SUCATA" },
  { id: "2550", name: "GERONIMO RECH DE ANDRADE", cargo: "OPER.TRATAMENTO TÉRMICO I", setor: "TRATAMENTO TÉRMICO" },
  { id: "2551", name: "JOSE EDSON FELINTO DA SILVA", cargo: "OP. REBARBAÇÃO (OP. ACAB.)III", setor: "LIXADEIRA MANUAL" },
  { id: "2558", name: "GILMAR EDSON BALDASSO", cargo: "INSPETOR QUALIDADE I", setor: "CONTROLE DE QUALIDADE" },
  { id: "2560", name: "VENICIUS SANTOS LEITE", cargo: "PANELEIRO (OPER. VAZAMENTO)II", setor: "VAZAMENTO" },
  { id: "2587", name: "CLEITON TELES DE JESUS", cargo: "ELETRICISTA I", setor: "MANUTENÇAO ELETRICA" },
  { id: "2598", name: "ADRIANO DA SILVA RIBEIRO", cargo: "SOLDADOR I", setor: "SOLDA" },
  { id: "2611", name: "MURILO NUNES FERNANDES", cargo: "MECÂNICO MANUTENÇÃO II", setor: "MANUTENÇAO MECANICA" },
  { id: "2618", name: "REGINALDO MIRA DE MELO", cargo: "SOLDADOR III", setor: "SOLDA" },
  { id: "2620", name: "WILLIAN GOMES LORENCO", cargo: "OPER. DE JATO (OPER. ACAB.)II", setor: "JATO GRANALHA" },
  { id: "2625", name: "EDVAN SANTOS DE ALENCAR", cargo: "OPER PROD MOLD FECH III", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "2629", name: "JOAO FRANCISCO KLEIS", cargo: "FRESADOR CNC (MODELAÇÃO) I", setor: "MODELARIA" },
  { id: "2640", name: "JULIANO SAO PEDRO SALES", cargo: "OP. COR. CANAL (MAÇARIQ.) II", setor: "CORTE DE CANAL MAÇARICO" },
  { id: "2643", name: "ANSELMO JOSE FAGUNDES DO NASCIMENTO", cargo: "OPER. DE JATO (OPER. ACAB.)I", setor: "ROTOJATO" },
  { id: "2645", name: "EDILSON MESSIAS GUIMARAES", cargo: "OP. REBARBAÇÃO (OP. ACAB.)III", setor: "LIXADEIRA MANUAL" },
  { id: "2648", name: "EDSON WELTER", cargo: "OPER.TRATAMENTO TÉRMICO III", setor: "TRATAMENTO TÉRMICO" },
  { id: "2653", name: "YAGO HENRIQUE GOMES DE LIMA", cargo: "OPERADOR DE PRODUÇÃO (SUCATA)II", setor: "SUCATA" },
  { id: "2663", name: "JEAN CARLOS RAMOS", cargo: "FRESADOR CNC (MODELAÇÃO) I", setor: "MODELARIA" },
  { id: "2664", name: "ISAAC JOELSON PAIVA GONÇALVES", cargo: "OPER. PRODUÇÃO MACHARIA II", setor: "MACHARIA" },
  { id: "2677", name: "ERIC ANDRADE DOS SANTOS", cargo: "OPER. DE SISTEMA DE AREIA III", setor: "DESMOLDAGEM" },
  { id: "2691", name: "ANTONIO DE SOUZA ARAUJO JUNIOR", cargo: "OPER. DE PROD. DESMOLDAGEM II", setor: "DESMOLDAGEM" },
  { id: "2694", name: "VALDEMAR DIAS", cargo: "OPER. REBARBAÇÃO (OP. ACAB.) II", setor: "PONTA MONTADA" },
  { id: "2715", name: "ALIFER IGOR FARIAS SANTOS", cargo: "OPERADOR PONTE ROLANTE II", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "2717", name: "VITUS ALEXANDRE HOH", cargo: "LIDER MODELAÇÃO", setor: "MODELARIA (I)" },
  { id: "2733", name: "LUIZ MARQUES GONSALES", cargo: "MECÂNICO MANUTENÇÃO I", setor: "MANUTENÇAO MECANICA" },
  { id: "2735", name: "MARCOS DURVAL ALBINO", cargo: "SOLDADOR II", setor: "SOLDA" },
  { id: "2737", name: "JOSE MODESTO CORDEIRO NETO", cargo: "OPERADOR ESPECIALISTA I", setor: "MACHARIA" },
  { id: "2745", name: "WALLISSON DA CONCEICAO CRUZ", cargo: "OPER. PRODUÇÃO MACHARIA II", setor: "MOLDAGEM COLDBOX" },
  { id: "2749", name: "LUAN SCHIAVON CASTRO", cargo: "LABORATORISTA I", setor: "LABORATORIO" },
  { id: "2754", name: "ADENILSON LIMA DE SOUZA", cargo: "OP. REBARBAÇÃO (OP. ACAB.)III", setor: "LIXADEIRA MANUAL" },
  { id: "2757", name: "JEFERSON SANTOS DA CONCEIÇÃO", cargo: "OPER. PRODUÇÃO MACHARIA II", setor: "MACHARIA" },
  { id: "2799", name: "SILVIO ROGERIO DOS SANTOS", cargo: "OPER. PRODUÇÃO MACHARIA II", setor: "MACHARIA" },
  { id: "2809", name: "RODRIGO DO NASCIMENTO", cargo: "OPER. PRODUÇÃO MACHARIA II", setor: "DEP. QUIMICOS E INFLAMAVEIS" },
  { id: "2828", name: "ADAILSON DOS SANTOS CORREA", cargo: "OPER. REBARBAÇÃO (OP. ACAB.)I", setor: "LIXADEIRA MANUAL" },
  { id: "2834", name: "BRUNO ANTONIO FUCK", cargo: "TORNEIRO MEC. (OPER. USI.)II", setor: "USINAGEM" },
  { id: "2840", name: "JOSUEL FELIX DO NASCIMENTO", cargo: "OPER. PRODUÇÃO MACHARIA II", setor: "MOLDAGEM COLDBOX" },
  { id: "2841", name: "ROBERTO LUCIO", cargo: "OPER. PRODUÇÃO MACHARIA II", setor: "MACHARIA" },
  { id: "2872", name: "RUAN PASSOS ANDRADE", cargo: "OPER. PRODUÇÃO MACHARIA II", setor: "MACHARIA" },
  { id: "2876", name: "ANDERSON ROBERTO RITA BARROS", cargo: "OP. REBARBAÇÃO (OP. ACAB.)III", setor: "LIXADEIRA MANUAL" },
  { id: "2882", name: "MAICON DEIVE ROSA", cargo: "MODELADOR I", setor: "MODELARIA" },
  { id: "2900", name: "FABIO JUNIOR BALBINO DA SILVA", cargo: "OP. DE ESCARFAGEM (OP. ACB)II", setor: "ESCARFAGEM" },
  { id: "2907", name: "THOMAS RICKSON FERREIRA DE JESUS", cargo: "OPER MAQ MOLD FECH II", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "2909", name: "THOMAS RICKSON FERREIRA DE JESUS", cargo: "OPER MAQ MOLD FECH II", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "2922", name: "Lucas Jose dos Santos", cargo: "OPER. REBARBAÇÃO (OP. ACAB.)I", setor: "ACABAMENTO DE PEÇAS" },
  { id: "2955", name: "LUAN SANTOS DA CONCEICAO", cargo: "OPER PROD MOLD FECH I", setor: "LINHA DE MOLDAGEM E FECHAMENTO" },
  { id: "2973", name: "NATHAN LEMES RECH", cargo: "ELETRICISTA DESENVOLV. II", setor: "MANUTENÇAO ELETRICA" },
  { id: "2978", name: "CLEITON DE JESUS SANTOS", cargo: "OPER. REBARBAÇÃO (OP. ACAB.) II", setor: "LIXADEIRA MANUAL" },
  { id: "3024", name: "PAULO SERRA DA SILVA", cargo: "OP. COR. CANAL (MAÇARICO) I", setor: "CORTE DE CANAL MAÇARICO" },
  { id: "3052", name: "BRUNO RICARDO RECH", cargo: "ALMOXARIFE I", setor: "LOGÍSTICA INTERNA" },
  { id: "3085", name: "ISRAEL NASCIMENTO SANTOS", cargo: "OPERADOR DE PRODUÇÃO (SUCATA)I", setor: "SUCATA" },
  { id: "3086", name: "KAUA GUIMARAES DA SILVA", cargo: "MONTADOR I", setor: "MANUTENÇAO MECANICA" },
  { id: "3101", name: "PEDRO HENRIQUE AMARAL", cargo: "REFRATARISTA I", setor: "FUSAO" },
  { id: "3116", name: "VITOR HUGO LACERDA", cargo: "PANELEIRO (OPER. VAZAMENTO)I", setor: "VAZAMENTO" },
  { id: "1995", name: "SANDRO ALEX RATES", cargo: "OPER.TRATAMENTO TÉRMICO I", setor: "TRATAMENTO TÉRMICO" },
  { id: "2169", name: "JOANDERSON DAVISSON BARBOSA DOS SANTOS", cargo: "OPER. DE SISTEMA DE AREIA III", setor: "DESMOLDAGEM" },
  { id: "2508", name: "ELIENAI DE SOUZA SILVA", cargo: "OPERADOR EMPILHADEIRA I", setor: "ACABAMENTO DE PEÇAS (I)" }
];

// Lista de equipamentos atualizada conforme a imagem
export const equipments: Equipment[] = [
  { id: "207", name: "Ponte 01", kp: "207", sector: "MOLDAGEM", capacity: "10 tons", type: "1" },
  { id: "409", name: "Ponte 02", kp: "409", sector: "DESMOLDAGEM", capacity: "10 tons", type: "1" },
  { id: "389", name: "Ponte 03", kp: "389", sector: "EXPEDIÇÃO", capacity: "5 tons", type: "1" },
  { id: "412", name: "Ponte 04", kp: "412", sector: "FUSAO", capacity: "3 tons", type: "1" },
  { id: "322", name: "Ponte 05", kp: "322", sector: "EXPEDIÇÃO", capacity: "1 ton", type: "1" },
  { id: "1092", name: "Ponte 06", kp: "1092", sector: "TRATAMENTO TÉRMICO", capacity: "5 tons", type: "1" },
  { id: "323", name: "Ponte 07", kp: "323", sector: "LINHA DE MOLDAGEM E FECHAMENTO", capacity: "5 e 16 tons", type: "1" },
  { id: "1325", name: "Ponte 08", kp: "1325", sector: "ACABAMENTO DE PEÇAS", capacity: "8 tons", type: "1" },
  { id: "1326", name: "Ponte 09", kp: "1326", sector: "FUSAO", capacity: "10 tons", type: "1" },
  { id: "1327", name: "Ponte 10", kp: "1327", sector: "ACABAMENTO DE PEÇAS", capacity: "2 tons", type: "1" },
  { id: "1270", name: "Ponte 11", kp: "1270", sector: "ACABAMENTO DE PEÇAS", capacity: "2 tons", type: "1" },
  { id: "215", name: "Ponte 12", kp: "215", sector: "MACHARIA", capacity: "1 ton", type: "1" },
  { id: "1804", name: "Ponte 13", kp: "1804", sector: "LINHA DE MOLDAGEM E FECHAMENTO", capacity: "2 tons", type: "1" },
  { id: "2686", name: "Ponte 14", kp: "2686", sector: "ACABAMENTO DE PEÇAS", capacity: "2 tons", type: "1" },
  { id: "3031", name: "Ponte 15", kp: "3031", sector: "FUSAO", capacity: "10 tons", type: "1" },
  { id: "3285", name: "Ponte 18", kp: "3285", sector: "MOLDAGEM", capacity: "1 ton", type: "1" },
  { id: "5846", name: "Ponte 19", kp: "5846", sector: "ACABAMENTO DE PEÇAS", capacity: "8 tons", type: "1" },
  { id: "6038", name: "Ponte 20", kp: "6038", sector: "LINHA DE MOLDAGEM E FECHAMENTO", capacity: "10 tons", type: "1" },
  { id: "6108", name: "Ponte 21", kp: "6108", sector: "ACABAMENTO DE PEÇAS", capacity: "2,5 tons", type: "1" },
  { id: "352", name: "Talha 19", kp: "352", sector: "SUCATA", capacity: "2 tons", type: "2" },
  { id: "375", name: "Talha 23", kp: "375", sector: "DESMOLDAGEM", capacity: "1 ton", type: "2" },
  { id: "3336", name: "Pórtico 01", kp: "3336", sector: "SUCATA", capacity: "5 tons", type: "3" },
  { id: "909", name: "Talha 11", kp: "909", sector: "FUSAO", capacity: "2 tons", type: "2" },
];

// Lista atualizada de verificações de segurança
export const checklistItems: ChecklistItem[] = [
  { id: "1", question: "Os cabos de aço apresentam fios partidos?", answer: null },
  { id: "2", question: "Os cabos de aço apresentam pontos de amassamento?", answer: null },
  { id: "3", question: "Os cabos de aço apresentam alguma dobra?", answer: null },
  { id: "4", question: "O sistema de freios do guincho está funcionando?", answer: null },
  { id: "5", question: "O gancho está girando sem dificuldades?", answer: null },
  { id: "6", question: "O gancho possui trava de segurança funcionando?", answer: null },
  { id: "7", question: "O gancho possui sinais de alongamento?", answer: null },
  { id: "8", question: "Os ganchos da corrente possuem sinais de desgaste?", answer: null },
  { id: "9", question: "As travas de segurança dos ganchos estão funcionando?", answer: null },
  { id: "10", question: "A corrente possui a plaqueta de identificação instalada?", answer: null },
  { id: "11", question: "As polias estão girando sem dificuldades?", answer: null },
  { id: "12", question: "A sinalização sonora funciona durante a movimentação?", answer: null },
  { id: "13", question: "O controle possui botão danificado?", answer: null },
  { id: "14", question: "O botão de emergência está funcionando?", answer: null },
  { id: "15", question: "A estrutura possui grandes danos?", answer: null },
  { id: "16", question: "O sistema de freios do Troller está funcionando?", answer: null },
  { id: "17", question: "Os elos da corrente possuem sinais de desgaste?", answer: null },
  { id: "18", question: "Os elos da corrente possuem sinais de 'alargamento'?", answer: null },
  { id: "19", question: "Os elos da corrente possuem sinais de 'alongamento'?", answer: null },
  { id: "20", question: "O fim de curso superior está funcionando?", answer: null },
  { id: "21", question: "O fim de curso inferior está funcionando?", answer: null },
  { id: "22", question: "O fim de curso direito está funcionando?", answer: null },
  { id: "23", question: "O fim de curso esquerdo está funcionando?", answer: null },
  { id: "24", question: "O equipamento apresenta ruídos estranhos?", answer: null },
];

